name: dog-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.1
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cryptography=38.0.4
  - cycler=0.11.0
  - dbus=1.13.18
  - dlib=19.24.0
  - eigen=3.4.0
  - expat=2.2.10
  - ffmpeg=4.2.2
  - flask=2.2.2
  - flatbuffers=2.0.0
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - freetype=2.10.4
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.7.0
  - harfbuzz=4.3.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - imutils=0.5.4
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - jpeg=9e
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcurl=7.87.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.4.3
  - multidict=6.0.2
  - ncurses=6.4
  - nettle=3.6
  - nspr=4.33
  - nss=3.74
  - numpy=1.22.3
  - oauthlib=3.2.1
  - openblas=0.3.20
  - opencv=4.6.0
  - openh264=2.1.1
  - openjpeg=2.3.1
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - packaging=22.0
  - pcre=8.45
  - pillow=9.3.0
  - pip=22.3.1
  - pixman=0.40.0
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.10
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.8.1
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.40.1
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.1.0
  - tk=8.6.12
  - tornado=6.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - waitress=2.1.2
  - werkzeug=2.2.2
  - wheel=0.37.1
  - wrapt=1.14.1
  - x264=1!157.20191217
  - xz=5.2.10
  - yarl=1.8.1
  - zipp=3.13.0
  - zlib=1.2.13
  - zstd=1.5.2